mark tags
abersheeran/django-simple-api pull request #24
Opened 2021-02-01 15:25 UTC by GJJ121785021

2021-02-02 08:49 UTC, waitan2018 approved these changes

2021-02-04 01:20 UTC, abersheeran requested changes

2021-02-04 01:20 UTC, abersheeran commented on django_simple_api/utils.py
> +    if isinstance(view, (list, tuple)):
`include` always return tuple.

2021-02-04 01:20 UTC, abersheeran commented on django_simple_api/utils.py
> +            "view must be a callable or a list/tuple in the case of include()."
a callable or a tuple in the case of `include()`

2021-02-04 12:21 UTC, abersheeran requested changes

2021-02-04 12:21 UTC, abersheeran commented on django_simple_api/utils.py
> +def wrapper_chain(wrappers: Sequence[Callable[[T], T]], view: T) -> T:
`view: Any`

2021-02-04 12:51 UTC, GJJ121785021 commented on django_simple_api/utils.py
> +def wrapper_chain(wrappers: Sequence[Callable[[T], T]], view: T) -> T:
done

2021-02-05 01:30 UTC, abersheeran commented on django_simple_api/utils.py
> +def wrapper_chain(wrappers: Sequence[Callable[[T], T]], view: Any) -> Any:
Maybe `wrapper_include` better than `wrapper_chain`.

2021-02-05 01:48 UTC, GJJ121785021 commented on django_simple_api/utils.py
> +def wrapper_chain(wrappers: Sequence[Callable[[T], T]], view: Any) -> Any:
done

2021-02-05 01:48 UTC, abersheeran submitted a review, later dismissed

2021-02-05 02:06 UTC, abersheeran approved these changes

2021-02-05 02:45 UTC, MeGustas-5427 approved these changes

2021-02-05 02:45 UTC, waitan2018 approved these changes

2021-02-05 02:46 UTC, merged