fix bug of type annotation.
abersheeran/django-simple-api pull request #25
Opened 2021-02-02 03:52 UTC by waitan2018

2021-02-02 04:27 UTC, GJJ121785021 submitted a review, later dismissed
Carefully check this

2021-02-02 12:50 UTC, abersheeran requested changes

2021-02-02 12:50 UTC, abersheeran commented on django_simple_api/params.py
> +            # If the view used `pydantic.fields` but not used type annotation, throw an exception.
```python
if annotation != param.empty:
    ...
else:
    raise TyperError(...)
```
Change to
```python
if annotation == param.empty:
    raise TypeError(...)
...
```

2021-02-03 02:22 UTC, GJJ121785021 approved these changes
Good code

2021-02-03 04:57 UTC, abersheeran approved these changes

2021-02-03 04:57 UTC, merged